var title  = 'Alfabeto';
var carpeta = 'alfabeto';

var videos = {
    'A'           : 'A.mp4',
    'B'           : 'B.mp4',
    'C'           : 'C.mp4',
    'D'           : 'D.mp4',
    'E'           : 'E.mp4',
    'F'           : 'F.mp4',
    'G'           : 'G.mp4',
    'H'           : 'H.mp4',
    'I'           : 'I.mp4',
    'J'           : 'J.mp4',
    'K'           : 'K.mp4',
    'L'           : 'L.mp4',
    'M'           : 'M.mp4',
    'N'           : 'N.mp4',
    'Ñ'           : 'Ñ.mp4',
    'O'           : 'O.mp4',
    'P'           : 'P.mp4',
    'Q'           : 'Q.mp4',
    'R'           : 'R.mp4',
    'S'           : 'S.mp4',
    'T'           : 'T.mp4',
    'U'           : 'U.mp4',
    'V'           : 'V.mp4',
    'W'           : 'W.mp4',
    'X'           : 'X.mp4',
    'Y'           : 'Y.mp4',
    'Z'           : 'Z.mp4',
};
